# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/srikanth/wip/eclispe_workspace/cpp_env_check

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/srikanth/wip/eclispe_workspace/cpp_env_check

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/srikanth/wip/eclispe_workspace/cpp_env_check/CMakeFiles /home/srikanth/wip/eclispe_workspace/cpp_env_check/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/srikanth/wip/eclispe_workspace/cpp_env_check/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lcov

# Build rule for target.
lcov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lcov
.PHONY : lcov

# fast build rule for target.
lcov/fast:
	$(MAKE) -f CMakeFiles/lcov.dir/build.make CMakeFiles/lcov.dir/build
.PHONY : lcov/fast

#=============================================================================
# Target rules for targets named cpp_env_check

# Build rule for target.
cpp_env_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_env_check
.PHONY : cpp_env_check

# fast build rule for target.
cpp_env_check/fast:
	$(MAKE) -f src/CMakeFiles/cpp_env_check.dir/build.make src/CMakeFiles/cpp_env_check.dir/build
.PHONY : cpp_env_check/fast

#=============================================================================
# Target rules for targets named cpp_env_check_tests

# Build rule for target.
cpp_env_check_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_env_check_tests
.PHONY : cpp_env_check_tests

# fast build rule for target.
cpp_env_check_tests/fast:
	$(MAKE) -f test/CMakeFiles/cpp_env_check_tests.dir/build.make test/CMakeFiles/cpp_env_check_tests.dir/build
.PHONY : cpp_env_check_tests/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lcov"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cpp_env_check"
	@echo "... cpp_env_check_tests"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

